### ISSUE TITLE
Add URL fetch alignment parameter for demo page

### ISSUE THREAD

**Issue by sacdallago** [sanderlab/AlignmentViewer2.0#18]
@npgauth a suggestion: add a url parameter to pass an alignment via URL in the demo page. The demo page works good enough as standalone (e.g. alignmentviewer.org). IF you allow people to pass an alignment via url parameter (`http://new.alignmentviewer.org/?url=https://my.domain/alignment.fa`, people can start using the tool today vs. figuring out how to integrate it into their webpages (which requires a bit more work + discussions +...).

I already have potential customers ;)

**Comment by npgauth** [comment]
Already done! (( like 2 days ago :-) ))

See: https://sanderlab.github.io/AlignmentViewer2.0/?alignment-url=https%3A%2F%2Fpfam.xfam.org%2Ffamily%2FPF00571%2Falignment%2Fseed

Note:

  1. The URL that points to the alignment must be served by https
  2. The URL that points to the alignment must be properly delimited 

Nick

**Comment by sacdallago** [comment]
Excellent! What timing..
